// Interface automatically generated by schemas-to-ts

import { Button } from '../../../../components/links/interfaces/Button';
import { Button_Plain } from '../../../../components/links/interfaces/Button';
import { Button_NoRelations } from '../../../../components/links/interfaces/Button';

export interface Test {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    sdf?: any;
    title?: any;
    links?: Button;
  };
}
export interface Test_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sdf?: any;
  title?: any;
  links?: Button_Plain;
}

export interface Test_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sdf?: any;
  title?: any;
  links?: Button_NoRelations;
}

export interface Test_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sdf?: any;
  title?: any;
  links?: Button_Plain;
}
