// Interface automatically generated by schemas-to-ts

import { Image } from '../../../../components/elements/interfaces/Image';
import { Image_Plain } from '../../../../components/elements/interfaces/Image';
import { Image_NoRelations } from '../../../../components/elements/interfaces/Image';

export interface Testimonial {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    client_name?: string;
    logo?: Image;
    client_organization?: string;
    testimonial?: string;
    locale: string;
    localizations?: { data: Testimonial[] };
  };
}
export interface Testimonial_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  client_name?: string;
  logo?: Image_Plain;
  client_organization?: string;
  testimonial?: string;
  locale: string;
  localizations?: Testimonial[];
}

export interface Testimonial_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  client_name?: string;
  logo?: Image_NoRelations;
  client_organization?: string;
  testimonial?: string;
  locale: string;
  localizations?: Testimonial[];
}

export interface Testimonial_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  client_name?: string;
  logo?: Image_Plain;
  client_organization?: string;
  testimonial?: string;
  locale: string;
  localizations?: Testimonial[];
}
