// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/test/interfaces/Media';
import { Category } from '../../../category/content-types/category/category';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Author } from '../../../author/content-types/author/author';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Author_Plain } from '../../../author/content-types/author/author';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description?: string;
    slug: string;
    cover?: { data: Media };
    categories?: { data: Category[] };
    seo?: Seo;
    authorsBio?: { data: Author };
    code: string;
    locale: string;
    localizations?: { data: Article[] };
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug: string;
  cover?: Media;
  categories?: Category_Plain[];
  seo?: Seo_Plain;
  authorsBio?: Author_Plain;
  code: string;
  locale: string;
  localizations?: Article[];
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug: string;
  cover?: number;
  categories?: number[];
  seo?: Seo_NoRelations;
  authorsBio?: number;
  code: string;
  locale: string;
  localizations?: Article[];
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug: string;
  cover?: AdminPanelRelationPropertyModification<Media>;
  categories?: AdminPanelRelationPropertyModification<Category_Plain>;
  seo?: Seo_Plain;
  authorsBio?: AdminPanelRelationPropertyModification<Author_Plain>;
  code: string;
  locale: string;
  localizations?: Article[];
}
