// Interface automatically generated by schemas-to-ts

export interface Languages {
  code?: any;
}
export interface Languages_Plain {
  code?: any;
}

export interface Languages_NoRelations {
  code?: any;
}

