// Interface automatically generated by schemas-to-ts

import { Media } from '../../test/interfaces/Media';

export interface Seo {
  metaTitle: string;
  metaDescription: string;
  shareImage?: { data: Media };
  keywords?: string;
  metaRobots?: string;
  structuredData?: any;
  metaViewport?: string;
  canonicalURL?: string;
}
export interface Seo_Plain {
  metaTitle: string;
  metaDescription: string;
  shareImage?: Media;
  keywords?: string;
  metaRobots?: string;
  structuredData?: any;
  metaViewport?: string;
  canonicalURL?: string;
}

export interface Seo_NoRelations {
  metaTitle: string;
  metaDescription: string;
  shareImage?: number;
  keywords?: string;
  metaRobots?: string;
  structuredData?: any;
  metaViewport?: string;
  canonicalURL?: string;
}

