// Interface automatically generated by schemas-to-ts

export interface Errors {
  messageNotFound?: string;
  messageNotFoundBlog?: string;
  returnMessageBlog?: string;
  returnMessageHome?: string;
}
export interface Errors_Plain {
  messageNotFound?: string;
  messageNotFoundBlog?: string;
  returnMessageBlog?: string;
  returnMessageHome?: string;
}

export interface Errors_NoRelations {
  messageNotFound?: string;
  messageNotFoundBlog?: string;
  returnMessageBlog?: string;
  returnMessageHome?: string;
}

