// Interface automatically generated by schemas-to-ts

import { Image } from '../../../../components/elements/interfaces/Image';
import { Image_Plain } from '../../../../components/elements/interfaces/Image';
import { Image_NoRelations } from '../../../../components/elements/interfaces/Image';

export interface Gallery {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description?: string;
    image?: Image;
    more: Image[];
  };
}
export interface Gallery_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  image?: Image_Plain;
  more: Image_Plain[];
}

export interface Gallery_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  image?: Image_NoRelations;
  more: Image_NoRelations[];
}

export interface Gallery_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description?: string;
  image?: Image_Plain;
  more: Image_Plain[];
}
