// Interface automatically generated by schemas-to-ts

import { Image } from '../../../../components/elements/interfaces/Image';
import { Errors } from '../../../../components/error/interfaces/Errors';
import { Image_Plain } from '../../../../components/elements/interfaces/Image';
import { Errors_Plain } from '../../../../components/error/interfaces/Errors';
import { Image_NoRelations } from '../../../../components/elements/interfaces/Image';
import { Errors_NoRelations } from '../../../../components/error/interfaces/Errors';

export interface Global {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    favicon?: Image;
    error?: Errors;
    locale: string;
    localizations?: { data: Global[] };
  };
}
export interface Global_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  favicon?: Image_Plain;
  error?: Errors_Plain;
  locale: string;
  localizations?: Global[];
}

export interface Global_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  favicon?: Image_NoRelations;
  error?: Errors_NoRelations;
  locale: string;
  localizations?: Global[];
}

export interface Global_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  favicon?: Image_Plain;
  error?: Errors_Plain;
  locale: string;
  localizations?: Global[];
}
