// Interface automatically generated by schemas-to-ts

export interface Navbar {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    links: any;
    locale: string;
    localizations?: { data: Navbar[] };
  };
}
export interface Navbar_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  links: any;
  locale: string;
  localizations?: Navbar[];
}

export interface Navbar_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  links: any;
  locale: string;
  localizations?: Navbar[];
}

export interface Navbar_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  links: any;
  locale: string;
  localizations?: Navbar[];
}
