// Interface automatically generated by schemas-to-ts

import { Image } from '../../../../components/elements/interfaces/Image';
import { Image_Plain } from '../../../../components/elements/interfaces/Image';
import { Image_NoRelations } from '../../../../components/elements/interfaces/Image';

export interface CordAcross {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    slug?: string;
    image?: Image;
  };
}
export interface CordAcross_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  image?: Image_Plain;
}

export interface CordAcross_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  image?: Image_NoRelations;
}

export interface CordAcross_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  slug?: string;
  image?: Image_Plain;
}
