// Interface automatically generated by schemas-to-ts

export interface Button {
  compoment?: any;
}
export interface Button_Plain {
  compoment?: any;
}

export interface Button_NoRelations {
  compoment?: any;
}

