// Interface automatically generated by schemas-to-ts

import { Media } from './Media';

export interface GridGalery {
  image?: { data: Media[] };
}
export interface GridGalery_Plain {
  image?: Media[];
}

export interface GridGalery_NoRelations {
  image?: number[];
}

