// Interface automatically generated by schemas-to-ts

export interface HeaderTitle_1 {
  title?: string;
  nameSection?: string;
  animation?: boolean;
}
export interface HeaderTitle_1_Plain {
  title?: string;
  nameSection?: string;
  animation?: boolean;
}

export interface HeaderTitle_1_NoRelations {
  title?: string;
  nameSection?: string;
  animation?: boolean;
}

