// Interface automatically generated by schemas-to-ts

import { Media } from '../../test/interfaces/Media';

export interface AniationCardGlsl {
  title?: string;
  image?: { data: Media };
}
export interface AniationCardGlsl_Plain {
  title?: string;
  image?: Media;
}

export interface AniationCardGlsl_NoRelations {
  title?: string;
  image?: number;
}

