// Interface automatically generated by schemas-to-ts

import { CustomImageCard } from '../../elements/interfaces/CustomImageCard';
import { CustomImageCard_Plain } from '../../elements/interfaces/CustomImageCard';
import { CustomImageCard_NoRelations } from '../../elements/interfaces/CustomImageCard';

export interface CustomGallery {
  title?: string;
  cards: CustomImageCard[];
}
export interface CustomGallery_Plain {
  title?: string;
  cards: CustomImageCard_Plain[];
}

export interface CustomGallery_NoRelations {
  title?: string;
  cards: CustomImageCard_NoRelations[];
}

