// Interface automatically generated by schemas-to-ts

import { CardCount } from '../../elements/interfaces/CardCount';
import { CardCount_Plain } from '../../elements/interfaces/CardCount';
import { CardCount_NoRelations } from '../../elements/interfaces/CardCount';

export interface CustomAbout {
  title: string;
  section: string;
  animation?: boolean;
  count: CardCount[];
}
export interface CustomAbout_Plain {
  title: string;
  section: string;
  animation?: boolean;
  count: CardCount_Plain[];
}

export interface CustomAbout_NoRelations {
  title: string;
  section: string;
  animation?: boolean;
  count: CardCount_NoRelations[];
}

