// Interface automatically generated by schemas-to-ts

import { AniationCardGlsl } from './AniationCardGlsl';
import { AniationCardGlsl_Plain } from './AniationCardGlsl';
import { AniationCardGlsl_NoRelations } from './AniationCardGlsl';

export interface CustomWork {
  title?: string;
  section?: string;
  animation?: boolean;
  crad: AniationCardGlsl[];
}
export interface CustomWork_Plain {
  title?: string;
  section?: string;
  animation?: boolean;
  crad: AniationCardGlsl_Plain[];
}

export interface CustomWork_NoRelations {
  title?: string;
  section?: string;
  animation?: boolean;
  crad: AniationCardGlsl_NoRelations[];
}

