// Interface automatically generated by schemas-to-ts

import { CustomAnimation } from '../../elements/interfaces/CustomAnimation';
import { CustomAboutUs } from '../../elements/interfaces/CustomAboutUs';
import { Image } from '../../elements/interfaces/Image';
import { ButtonLink } from '../../links/interfaces/ButtonLink';
import { CustomAnimation_Plain } from '../../elements/interfaces/CustomAnimation';
import { CustomAboutUs_Plain } from '../../elements/interfaces/CustomAboutUs';
import { Image_Plain } from '../../elements/interfaces/Image';
import { ButtonLink_Plain } from '../../links/interfaces/ButtonLink';
import { CustomAnimation_NoRelations } from '../../elements/interfaces/CustomAnimation';
import { CustomAboutUs_NoRelations } from '../../elements/interfaces/CustomAboutUs';
import { Image_NoRelations } from '../../elements/interfaces/Image';
import { ButtonLink_NoRelations } from '../../links/interfaces/ButtonLink';

export interface CustomHeader {
  title: string;
  animation?: CustomAnimation;
  about_us?: CustomAboutUs;
  image: Image;
  button: ButtonLink;
}
export interface CustomHeader_Plain {
  title: string;
  animation?: CustomAnimation_Plain;
  about_us?: CustomAboutUs_Plain;
  image: Image_Plain;
  button: ButtonLink_Plain;
}

export interface CustomHeader_NoRelations {
  title: string;
  animation?: CustomAnimation_NoRelations;
  about_us?: CustomAboutUs_NoRelations;
  image: Image_NoRelations;
  button: ButtonLink_NoRelations;
}

