// Interface automatically generated by schemas-to-ts

import { Question } from '../../elements/interfaces/Question';
import { Question_Plain } from '../../elements/interfaces/Question';
import { Question_NoRelations } from '../../elements/interfaces/Question';

export interface CustomQuestions {
  title?: string;
  asked_questions: Question[];
}
export interface CustomQuestions_Plain {
  title?: string;
  asked_questions: Question_Plain[];
}

export interface CustomQuestions_NoRelations {
  title?: string;
  asked_questions: Question_NoRelations[];
}

