// Interface automatically generated by schemas-to-ts

import { CordAcross } from '../../../api/cord-across/content-types/cord-across/cord-across';
import { CordAcross_Plain } from '../../../api/cord-across/content-types/cord-across/cord-across';

export interface CustomAcross {
  title?: string;
  card_acrosses: { data: CordAcross[] };
}
export interface CustomAcross_Plain {
  title?: string;
  card_acrosses: CordAcross_Plain[];
}

export interface CustomAcross_NoRelations {
  title?: string;
  card_acrosses: number[];
}

