// Interface automatically generated by schemas-to-ts

import { CustomCardChoose } from '../../elements/interfaces/CustomCardChoose';
import { CustomCardChoose_Plain } from '../../elements/interfaces/CustomCardChoose';
import { CustomCardChoose_NoRelations } from '../../elements/interfaces/CustomCardChoose';

export interface CustomChoose {
  title?: string;
  card_list: CustomCardChoose[];
}
export interface CustomChoose_Plain {
  title?: string;
  card_list: CustomCardChoose_Plain[];
}

export interface CustomChoose_NoRelations {
  title?: string;
  card_list: CustomCardChoose_NoRelations[];
}

