// Interface automatically generated by schemas-to-ts

import { Testimonial } from '../../../api/testimonial/content-types/testimonial/testimonial';
import { Testimonial_Plain } from '../../../api/testimonial/content-types/testimonial/testimonial';

export interface TestimonialComponent {
  title?: string;
  testimonials: { data: Testimonial[] };
}
export interface TestimonialComponent_Plain {
  title?: string;
  testimonials: Testimonial_Plain[];
}

export interface TestimonialComponent_NoRelations {
  title?: string;
  testimonials: number[];
}

