// Interface automatically generated by schemas-to-ts

import { Logo } from './Logo';
import { Link } from '../../../api/link/content-types/link/link';
import { Logo_Plain } from './Logo';
import { Link_Plain } from '../../../api/link/content-types/link/link';
import { Logo_NoRelations } from './Logo';

export interface FooterComponent {
  logoFooter?: Logo;
  adres?: string;
  kodPocztowy?: string;
  nip?: number;
  footer_links: { data: Link[] };
}
export interface FooterComponent_Plain {
  logoFooter?: Logo_Plain;
  adres?: string;
  kodPocztowy?: string;
  nip?: number;
  footer_links: Link_Plain[];
}

export interface FooterComponent_NoRelations {
  logoFooter?: Logo_NoRelations;
  adres?: string;
  kodPocztowy?: string;
  nip?: number;
  footer_links: number[];
}

