// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface Logo {
  logo?: { data: Media };
  alt?: string;
}
export interface Logo_Plain {
  logo?: Media;
  alt?: string;
}

export interface Logo_NoRelations {
  logo?: number;
  alt?: string;
}

