// Interface automatically generated by schemas-to-ts

import { Logo } from './Logo';
import { Languages } from '../../shared/interfaces/Languages';
import { Logo_Plain } from './Logo';
import { Languages_Plain } from '../../shared/interfaces/Languages';
import { Logo_NoRelations } from './Logo';
import { Languages_NoRelations } from '../../shared/interfaces/Languages';

export interface NavbarComponent {
  logo?: Logo;
  Languages: Languages[];
}
export interface NavbarComponent_Plain {
  logo?: Logo_Plain;
  Languages: Languages_Plain[];
}

export interface NavbarComponent_NoRelations {
  logo?: Logo_NoRelations;
  Languages: Languages_NoRelations[];
}

