// Interface automatically generated by schemas-to-ts

import { Article } from '../../../article/content-types/article/article';
import { Article_Plain } from '../../../article/content-types/article/article';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Category {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description?: string;
    slug?: string;
    articles?: { data: Article[] };
    locale: string;
    localizations?: { data: Category[] };
  };
}
export interface Category_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  articles?: Article_Plain[];
  locale: string;
  localizations?: Category[];
}

export interface Category_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  articles?: number[];
  locale: string;
  localizations?: Category[];
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description?: string;
  slug?: string;
  articles?: AdminPanelRelationPropertyModification<Article_Plain>;
  locale: string;
  localizations?: Category[];
}
