// Interface automatically generated by schemas-to-ts

export interface CardCount {
  start: number;
  end: number;
  delay?: number;
  leftText?: string;
  rightText?: string;
  name: string;
}
export interface CardCount_Plain {
  start: number;
  end: number;
  delay?: number;
  leftText?: string;
  rightText?: string;
  name: string;
}

export interface CardCount_NoRelations {
  start: number;
  end: number;
  delay?: number;
  leftText?: string;
  rightText?: string;
  name: string;
}

