// Interface automatically generated by schemas-to-ts

import { Media } from '../../test/interfaces/Media';

export interface CustomImageCard {
  title?: string;
  description?: string;
  image?: { data: Media };
  alt?: string;
}
export interface CustomImageCard_Plain {
  title?: string;
  description?: string;
  image?: Media;
  alt?: string;
}

export interface CustomImageCard_NoRelations {
  title?: string;
  description?: string;
  image?: number;
  alt?: string;
}

