// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface CustomCardAcross {
  title?: string;
  image?: { data: Media };
  alt?: string;
  url?: string;
  slug?: any;
}
export interface CustomCardAcross_Plain {
  title?: string;
  image?: Media;
  alt?: string;
  url?: string;
  slug?: any;
}

export interface CustomCardAcross_NoRelations {
  title?: string;
  image?: number;
  alt?: string;
  url?: string;
  slug?: any;
}

