// Interface automatically generated by schemas-to-ts

import { Media } from '../../test/interfaces/Media';

export interface CustomAnimation {
  image?: { data: Media };
  base_velocity?: number;
  view?: boolean;
}
export interface CustomAnimation_Plain {
  image?: Media;
  base_velocity?: number;
  view?: boolean;
}

export interface CustomAnimation_NoRelations {
  image?: number;
  base_velocity?: number;
  view?: boolean;
}

