// Interface automatically generated by schemas-to-ts

export interface CustomAboutUs {
  title?: string;
  description?: string;
  left?: string;
  right?: string;
}
export interface CustomAboutUs_Plain {
  title?: string;
  description?: string;
  left?: string;
  right?: string;
}

export interface CustomAboutUs_NoRelations {
  title?: string;
  description?: string;
  left?: string;
  right?: string;
}

