// Interface automatically generated by schemas-to-ts

export interface CustomCardChoose {
  title?: string;
  description?: string;
}
export interface CustomCardChoose_Plain {
  title?: string;
  description?: string;
}

export interface CustomCardChoose_NoRelations {
  title?: string;
  description?: string;
}

