// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface CustomTestimonialsCard {
  logo?: { data: Media };
  alt?: string;
  description?: string;
  name?: string;
  organizacja?: string;
}
export interface CustomTestimonialsCard_Plain {
  logo?: Media;
  alt?: string;
  description?: string;
  name?: string;
  organizacja?: string;
}

export interface CustomTestimonialsCard_NoRelations {
  logo?: number;
  alt?: string;
  description?: string;
  name?: string;
  organizacja?: string;
}

