// Interface automatically generated by schemas-to-ts

import { Link } from '../../../api/link/content-types/link/link';
import { Category } from '../../../api/category/content-types/category/category';
import { Link_Plain } from '../../../api/link/content-types/link/link';
import { Category_Plain } from '../../../api/category/content-types/category/category';

export interface FooterLink {
  title?: string;
  link: { data: Link[] };
  categorie: { data: Category[] };
}
export interface FooterLink_Plain {
  title?: string;
  link: Link_Plain[];
  categorie: Category_Plain[];
}

export interface FooterLink_NoRelations {
  title?: string;
  link: number[];
  categorie: number[];
}

