// Interface automatically generated by schemas-to-ts

import { Media } from '../../test/interfaces/Media';

export interface Image {
  image?: { data: Media };
  alt?: string;
}
export interface Image_Plain {
  image?: Media;
  alt?: string;
}

export interface Image_NoRelations {
  image?: number;
  alt?: string;
}

