// Interface automatically generated by schemas-to-ts

export interface Question {
  title_question: string;
  Reply: string;
}
export interface Question_Plain {
  title_question: string;
  Reply: string;
}

export interface Question_NoRelations {
  title_question: string;
  Reply: string;
}

