// Interface automatically generated by schemas-to-ts

import { LinkComponent } from './LinkComponent';
import { LinkComponent_Plain } from './LinkComponent';
import { LinkComponent_NoRelations } from './LinkComponent';

export interface ColectionLinks {
  title?: string;
  link: LinkComponent[];
}
export interface ColectionLinks_Plain {
  title?: string;
  link: LinkComponent_Plain[];
}

export interface ColectionLinks_NoRelations {
  title?: string;
  link: LinkComponent_NoRelations[];
}

