// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Link_Plain } from './Link';
import { Link_NoRelations } from './Link';

export interface ColectionLink {
  title?: string;
  link: Link[];
}
export interface ColectionLink_Plain {
  title?: string;
  link: Link_Plain[];
}

export interface ColectionLink_NoRelations {
  title?: string;
  link: Link_NoRelations[];
}

