// Interface automatically generated by schemas-to-ts

import { LinkComponent } from './LinkComponent';
import { LinkComponent_Plain } from './LinkComponent';
import { LinkComponent_NoRelations } from './LinkComponent';

export interface LinkNavigation {
  title?: string;
  link?: string;
  newTab?: boolean;
  links: LinkComponent[];
}
export interface LinkNavigation_Plain {
  title?: string;
  link?: string;
  newTab?: boolean;
  links: LinkComponent_Plain[];
}

export interface LinkNavigation_NoRelations {
  title?: string;
  link?: string;
  newTab?: boolean;
  links: LinkComponent_NoRelations[];
}

