// Interface automatically generated by schemas-to-ts

export interface LinkComponent {
  newTab?: boolean;
  title?: string;
  link?: string;
}
export interface LinkComponent_Plain {
  newTab?: boolean;
  title?: string;
  link?: string;
}

export interface LinkComponent_NoRelations {
  newTab?: boolean;
  title?: string;
  link?: string;
}

