// Interface automatically generated by schemas-to-ts

export enum Social {
  Youtube = 'YOUTUBE',
  Twitter = 'TWITTER',
  Discord = 'DISCORD',
  Instagram = 'INSTAGRAM',
  Linkedin = 'LINKEDIN',
  Facebook = 'FACEBOOK',}

export interface SocialLink {
  url?: string;
  newTab?: boolean;
  social?: Social;
}
export interface SocialLink_Plain {
  url?: string;
  newTab?: boolean;
  social?: Social;
}

export interface SocialLink_NoRelations {
  url?: string;
  newTab?: boolean;
  social?: Social;
}

