// Interface automatically generated by schemas-to-ts

import { LinkComponent } from '../../../../components/links/interfaces/LinkComponent';
import { LinkComponent_Plain } from '../../../../components/links/interfaces/LinkComponent';
import { LinkComponent_NoRelations } from '../../../../components/links/interfaces/LinkComponent';

export interface Link {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    links: LinkComponent[];
    locale: string;
    localizations?: { data: Link[] };
  };
}
export interface Link_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  links: LinkComponent_Plain[];
  locale: string;
  localizations?: Link[];
}

export interface Link_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  links: LinkComponent_NoRelations[];
  locale: string;
  localizations?: Link[];
}

export interface Link_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  links: LinkComponent_Plain[];
  locale: string;
  localizations?: Link[];
}
