/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import slug from "custom-slug/strapi-admin";
import strapiAdvancedUuid from "strapi-advanced-uuid/strapi-admin";
import componentpreview from "strapi-plugin-component-preview/strapi-admin";
import countrySelect from "strapi-plugin-country-select/strapi-admin";
import customLinks from "strapi-plugin-custom-links/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import pptCustomfields from "strapi-plugin-ppt-customfields/strapi-admin";
import protectedPopulate from "strapi-plugin-protected-populate/strapi-admin";
import wysiwygReactMdEditor from "strapi-plugin-wysiwyg-react-md-editor/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "drag-drop-content-types": dragDropContentTypes,
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    slug: slug,
    "strapi-advanced-uuid": strapiAdvancedUuid,
    componentpreview: componentpreview,
    "country-select": countrySelect,
    "custom-links": customLinks,
    navigation: navigation,
    "ppt-customfields": pptCustomfields,
    "protected-populate": protectedPopulate,
    "wysiwyg-react-md-editor": wysiwygReactMdEditor,
  },
});
