// Interface automatically generated by schemas-to-ts

import { Image } from '../../../../components/elements/interfaces/Image';
import { SocialLink } from '../../../../components/links/interfaces/SocialLink';
import { Link } from '../../../link/content-types/link/link';
import { Image_Plain } from '../../../../components/elements/interfaces/Image';
import { SocialLink_Plain } from '../../../../components/links/interfaces/SocialLink';
import { Link_Plain } from '../../../link/content-types/link/link';
import { Image_NoRelations } from '../../../../components/elements/interfaces/Image';
import { SocialLink_NoRelations } from '../../../../components/links/interfaces/SocialLink';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Footer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    contentSections?: any;
    adres: string;
    name: string;
    nip?: string;
    email: string;
    logo: Image;
    social: SocialLink[];
    links: { data: Link[] };
    locale: string;
    localizations?: { data: Footer[] };
  };
}
export interface Footer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contentSections?: any;
  adres: string;
  name: string;
  nip?: string;
  email: string;
  logo: Image_Plain;
  social: SocialLink_Plain[];
  links: Link_Plain[];
  locale: string;
  localizations?: Footer[];
}

export interface Footer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contentSections?: any;
  adres: string;
  name: string;
  nip?: string;
  email: string;
  logo: Image_NoRelations;
  social: SocialLink_NoRelations[];
  links: number[];
  locale: string;
  localizations?: Footer[];
}

export interface Footer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  contentSections?: any;
  adres: string;
  name: string;
  nip?: string;
  email: string;
  logo: Image_Plain;
  social: SocialLink_Plain[];
  links: AdminPanelRelationPropertyModification<Link_Plain>;
  locale: string;
  localizations?: Footer[];
}
