// Interface automatically generated by schemas-to-ts

import { Button } from '../../links/interfaces/Button';
import { Button_Plain } from '../../links/interfaces/Button';
import { Button_NoRelations } from '../../links/interfaces/Button';

export interface Newsletter {
  title: string;
  button: Button;
  email: string;
}
export interface Newsletter_Plain {
  title: string;
  button: Button_Plain;
  email: string;
}

export interface Newsletter_NoRelations {
  title: string;
  button: Button_NoRelations;
  email: string;
}

